### ISSUE TITLE
Leitura da section de Adicionando Interatividade

### ISSUE THREAD

**Issue by JVictorV** [RenanVidal/sopa-de-letrinhas#1]
https://pt-br.react.dev/learn/adding-interactivity
- [x] Adicionando Interatividade
- [x] Respondendo a Eventos
- [x] Estado: Memoria de um Componente
- [x] Renderizar e Confirmar
- [x] Estado como um Snapshot
- [x] Enfileirando uma Serie de Atualizacoes de Estado
- [x] Atualizando Objetos no Estado
- [x] Atualizando Vetores no Estado

**Comment by RenanVidal** [comment]
Li novamente o Estado de memoria e fiz os exercícios do mesmo e já comecei a ler o "Renderizar e Confirmar"!

**Comment by RenanVidal** [comment]
Finalizado
